# fly.toml app configuration file generated for phonebook-restless-sun-7134 on 2024-08-19T12:46:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-restless-sun-7134'
primary_region = 'mad'

[build]
  
[env]
  PORT = "3000" # add this where PORT matches the internal_port below

[processes]
  app = "node index.js" # add this

[deploy]
  strategy = 'canary'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

